language: cpp
compiler: gcc
cache: apt
before_install:
  - sudo add-apt-repository ppa:mikepurvis/stm32 -y
  - sudo apt-get update
install:
  - sudo apt-get install stm32plus-headers stm32plus-small-f4-8000000 -y
script:
  - mkdir build && cd build
  - cmake ..
  - make blink.bin
  - arm-none-eabi-size blink
